### ISSUE TITLE
No access to the thread pool that loads config

### ISSUE THREAD

**Issue by tobyweston** [oncue/knobs#25]
It looks like :small_blue_diamond: the `loadp` method in [`knobs/package.scala`](https://github.com/oncue/knobs/blob/master/core/src/main/scala/knobs/package.scala) doesn't give access to the thread pool used to load stuff.

Can we get access to this?

perhaps changing
✝
```scala
private [knobs] def loadp(paths: List[(Name, KnobsResource)]): Task[BaseConfig] = for {
    // snip
    _ <- Task(ticks.evalMap(_ => bc.reload).run.runAsync(_.fold(_.printStackTrace, _ => ())))
  } yield bc
```

to something like this

```scala
private [knobs] def loadp(paths: List[(Name, KnobsResource)])(implicit pool: ExecutorService = Strategy.DefaultExecutorService): Task[BaseConfig] = for {
    // snip
    _ <- Task(ticks.evalMap(_ => bc.reload).run.runAsync(_.fold(_.printStackTrace, _ => ())))(pool)
  } yield bc
```
and chain it up to the public `load`/`loadImmutable` methods?

:small_blue_diamond: correct me if I'm wrong

**Comment by runarorama** [comment]
Well, the `bc.reload` is what controls which thread loads things. The `loadp` method just schedules that to happen at some point. It should either call `Task.fork` instead of `Task(_)`, or it should call Task.async to register a callback when `bc.load` has finished.

**Comment by tobyweston** [comment]
hmm, not sure I get that. I'll poke around to see if I can get it to make sense... :smile: 

As background, I got interested because I get _n_ threads created by the default pool (named the usual `pool-1-thread-2` type thing) which I couldn't track down, and suspect they come from the above. I'd like to be able to name them, eg, if they're from knobs, something like `knobs-config-loader-thread-n`.
