### ISSUE TITLE
Make watching file resources optional

### ISSUE THREAD

**Issue by runarorama** [oncue/knobs#4]
Currently a `FileResource` will always result in a `Watch`ed resource. I think this should probably be optional, as sometimes you know that a file is not going to change, or you do not want your config to reload if it does, or you want to always explicitly reload.

**Comment by timperrett** [comment]
Agreed - watching files should be something one explicitly states, as i think mutability is the uncommon case.

**Comment by runarorama** [comment]
Fixed by #17 and #18
