### ISSUE TITLE
Type Mismatch Error following Usage example for ClassPathResource

### ISSUE THREAD

**Issue by tperrigo** [oncue/knobs#6]
Greetings,
I just tried loading a ClassPathResource, following the example in the [Usage](http://oncue.github.io/knobs/usage) documentation, but I'm getting a type mismatch error...I'm guessing I'm missing something extremely basic, but for the moment I'm stumped...here's the example (I've tried using knobs-core 3.2.1 and 3.2.2-SNAPSHOT):

```scala
import knobs._
import scalaz.concurrent.Task

val config: Task[Config] = knobs.loadImmutable(Required(ClassPathResource("knobs-example.cfg")))

<console>:20: error: type mismatch;
 found   : knobs.Required[knobs.ResourceBox]
 required: List[knobs.KnobsResource]
    (which expands to)  List[knobs.Worth[knobs.ResourceBox]]
       val config: Task[Config] = knobs.loadImmutable(Required(ClassPathResource("knobs-example.cfg")))
```

Am I missing or misunderstanding something simple here?  Any help would be appreciated.
Thanks,
Tim

**Comment by timperrett** [comment]
@tperrigo oh, `loadImmutable` takes a list :-) Try:

```
val config: Task[Config] = knobs.loadImmutable(Required(ClassPathResource("knobs-example.cfg")) :: Nil)
```

**Comment by rintcius** [comment]
Fixed it as part of https://github.com/oncue/knobs/pull/9 
Nice feature of `tut` is don't it can actually interpret the code (and fail the build if it encounters errors).
